[[redirects]]
  from = "/cv"
  to = "https://bit.ly/3lpGWJN"
  status = 200
  force = true

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/839nNUP"
  status = 200
  force = true

[[redirects]]
  from = "/tw"
  to = "https://twitter.com/edgar_mmejia"
  status = 200
  force = true

[[redirects]]
  from = "/stack"
  to = "https://stackoverflow.com/users/9200447"
  status = 200
  force = true

[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/mejia-edgar/"
  status = 200
  force = true

[[redirects]]
  from = "/fb"
  to = "https://www.facebook.com/mmejia.edgar/"
  status = 200
  force = true
